In [2]:
import numpy as np

## 1D Array Creation in numpy

In [22]:
arr=np.array([1,2,3,4,5]) 
print(type(arr))
print(arr)
print(arr.dtype) #data type of the array
print(arr.size)
print(arr.ndim)
print(arr.shape)

# Access The Element Of The array
print(arr[3])

<class 'numpy.ndarray'>
[1 2 3 4 5]
int64
5
1
(5,)
4


### 0D Array

In [16]:
a1=np.array(10,dtype='i4',ndmin=2) # set the dimension by user
print(a1)       
print(a1.dtype) #data type of the array
print(a1.size)
print(a1.ndim)
print(a1.shape)

# Access The Element Of The array
print(a1[0])

[[10]]
int32
1
2
(1, 1)
[10]


## 2D Array in The Numpy

In [62]:
a1=[[1,2,3],[4,5,6],[7,8,9]]
print(a1)
print(a1[0][2])
print(a1[1][1])
print(a1[-1][-3])
print(a1[-1])
print(a1[-2][-2])
a1[-3][-2]=100 # here you Can Assign Value to a elements
print(a1)
a2=np.array([[1,2],[3,'4']],) #it Automatically Converted it into string so you provide the Type
print(a2)
print(a2.dtype)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3
5
7
[7, 8, 9]
5
[[1, 100, 3], [4, 5, 6], [7, 8, 9]]
[['1' '2']
 ['3' '4']]
<U21


## 3D Array in Numpy

In [70]:
a1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a1)
print(a1.dtype)
print(a1.size)
print(a1.ndim)
print(a1.shape)

# Acess The Element Of The 3D Array
print(a1[0,0,0])
print(a1[0,1,0])
print(a1[1,0,1])
print(a1[1,1,1])
print(a1[-1,-1,-2])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
int64
8
3
(2, 2, 2)
1
3
6
8
7


## Creating Different Type Of Numpy Array


In [58]:
# you have to be print array which contains only zeros values

ar=np.zeros((3,4)) # Bydefault it return a float value
print(ar)
ar[1][2]=np.nan # You can add NAN Value to the Array
print(ar)

arr=np.zeros((4,3),dtype='i') # you caan set the dtype to int i.e i
print(arr)

arr1=np.ones((2,2),dtype='i') # Bydefault it return a float value
print(arr1)

arr3=np.full((3,4),5,dtype='i') # Bydefault it return a float value
print(arr3)

arr4=np.arange(1,10)
print(arr4)
arr4.reshape((3,3)) # The arr4 value remains same it does not affect the original arr4

arr5=np.random.rand(3,4) # Generate Random Value
print(arr5)

arr6=np.random.randint(8,size=(3,4)) # Generate Random value From 0 to 8
print(arr6)

arr7=np.random.randint(5,10,size=(3,4)) # Generate Random Number Between 5 to 10
print(arr7)

arr8=np.identity(3,dtype='i') # Bydefault it return a float value so You Provide The dtype='i'
print(arr8)

arr9=np.linspace(1,10,3)
print(arr9)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ 0.  0.  0.  0.]
 [ 0.  0. nan  0.]
 [ 0.  0.  0.  0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[1 2 3 4 5 6 7 8 9]
[[0.90699558 0.44145365 0.0217057  0.26182827]
 [0.32886819 0.62520854 0.0533297  0.68234868]
 [0.18001517 0.88436868 0.27622503 0.12327427]]
[[0 7 5 0]
 [5 3 6 1]
 [2 5 6 6]]
[[5 6 9 8]
 [9 7 6 6]
 [5 8 5 6]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[ 1.   5.5 10. ]


## Slicing in 1D Array

In [75]:
arr=np.array([10,20,30,40,50])
print(arr[::])
print(arr[::-1])
print(arr[2::])
print(arr[:3:])
print(arr[3::-1])

[10 20 30 40 50]
[50 40 30 20 10]
[30 40 50]
[10 20 30]
[40 30 20 10]


## Slicing in 2D Array

In [6]:
a1=[[1,2,3],[4,5,6],[7,8,9]]
print(a1[::-1])
print(a1[ ::,  1::])



[[7, 8, 9], [4, 5, 6], [1, 2, 3]]


TypeError: list indices must be integers or slices, not tuple

# Craeting Structure Array

In [33]:
# First way to create Structure Array
a1=np.array([('Sashi',22,65),('Ashish',21,55),('Priyam',20,62)],dtype=[('name','U10'),('age','i'),('weight','f')])
print(a1)
print(a1[0])
print(a1['name']) # You can Print Name value
print(a1['age'])  # You can Print age value
print(a1['weight'])  # You can Print weight value
a1[2][1]=25
print(a1)
a1[1]['age']=18 # You Change The Age Value
print(a1['age'])
print(a1)

# Second Way to create structure Array
a2=np.array([('kamal',22,65),('Binay',21,55),('Bapun',20,62)],dtype=('U10,i,f'))
print(a2)
print(a2['f0'])
print(a2['f1'])
print(a2['f2'])

# Third Way to create the structure array
a3=np.array([('sanjay',22,65),('Laxman',21,55),('khilar',20,62)],dtype={'names':['name','age','weight'],'formats':['U10','i','f']})
print(a3)
print(a3['name']) 
print(a3['age'])             # Here only the dtype format is going to be change.
print(a3['weight'])        

# Fourth Way to create the structure array

a4=np.array([('Sairam',22,65),('Maa',21,55),('Jay',20,62)],dtype={'name':('U10',0),'age':('i',1),'weight':('f',2)})
print(a4)



[('Sashi', 22, 65.) ('Ashish', 21, 55.) ('Priyam', 20, 62.)]
('Sashi', 22, 65.0)
['Sashi' 'Ashish' 'Priyam']
[22 21 20]
[65. 55. 62.]
[('Sashi', 22, 65.) ('Ashish', 21, 55.) ('Priyam', 25, 62.)]
[22 18 25]
[('Sashi', 22, 65.) ('Ashish', 18, 55.) ('Priyam', 25, 62.)]
[('kamal', 22, 65.) ('Binay', 21, 55.) ('Bapun', 20, 62.)]
['kamal' 'Binay' 'Bapun']
[22 21 20]
[65. 55. 62.]
[('sanjay', 22, 65.) ('Laxman', 21, 55.) ('khilar', 20, 62.)]
['sanjay' 'Laxman' 'khilar']
[22 21 20]
[65. 55. 62.]
[('ᙓ䊂iram', -2113929194, 65.) ('ᕍ䉜a',  1543503893, 55.)
 ('ᑊ䉸y',  2013265940, 62.)]


# Broadcasting in Numpy

In [3]:
a1=np.full(3,(3,),dtype='i' )     # a1=np.zeros([3,],dtype='i') You can also write this way
print(a1) 
a=a1+5 # Broadcasting is possible
print(a)

a2=np.array([[1],[2],[3]])
print(a1+a2)

#print(np.array([1,2,3,4])+np.array([5,6,7])) # Broadcasting is not possible

"""
b1=np.ones([2,3,5])
b2=np.zeros([4,1,5])
print(b1+b2)
"""
'''
b1=np.ones([10,9,8,7])
b2=np.zeros([1,7])
print(b1+b2)
'''

[3 3 3]
[8 8 8]
[[4 4 4]
 [5 5 5]
 [6 6 6]]


'\nb1=np.ones([10,9,8,7])\nb2=np.zeros([1,7])\nprint(b1+b2)\n'

# Array Manipulation

In [35]:
# addition
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[7,8,9],[1,4,7]])
res=a1+a2
print(res)
print(np.add(a1,a2)) # Inbuilt Method
# subtraction
print(a1-a2)
print(np.subtract(a1,a2))
# Multiplication
print(a1*a2)
print(np.multiply(a1,a2))
# Division
print(a1/a2)
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
print(x+y)

# Iteration over matrix
for i in res:
    for j in i:
        print(j,end=" ")

# Default Method
for i in np.nditer(res):
    print(i)
# Enumerator 
for i,j in np.ndenumerate(res):
    print("{1} is in index {0}".format(i,j))

#Concatenation of array
a=np.array([12,3,4,5])
b=np.array([78,3,4,5])
c=np.concatenate((a,b)) # in concatenate the data in horizontally
print(c)

s=np.stack((a,b)) # Show The Element in column wise 
print(s)

h=np.hstack((a,b)) # Horinzontal Stack 
print(h)

v=np.vstack((a,b)) # Vertical Stack 
print(v)

d=np.dstack((a,b)) # Deapth Satck 
print(d)

x=np.stack((a,b),axis=1) # Show The Element is same as D stack
print(x)


####################################

b1=np.array([[10,20],[30,40]])
b2=np.array([[1,2],[3,4]])       # It Just Show The Array in 2D Format and this is same for axis=0
print(np.concatenate((b1,b2),axis=0))

print(np.concatenate((b1,b2),axis=1)) # It Print where axis=1 it is also Similar to Dstack() method.

# Split The Array into different Parts

st=np.array([10,55,90,78])
print(np.array_split(st,3)) # Split The 1D Array.
print(np.array_split(b1,4)) # Split 3D array

# Searching in Array.......

sr=np.array([1,5,2,34,2,4,3,4,5])
x=np.where(sr==4)
print(x) # It only return the index of the array.
print(np.where(sr%2==0))

print(np.where(b1==30)) # Search in 2D Array.

#Sort The array....
st=np.array([10,55,90,78])
res=np.sort(st)
print(res)

b4=np.array([[167,20,10],[456,900,9]])
r=np.sort(b4,axis=1)  # here bydefault the axis=1.
print(r)

s=np.sort(b4,axis=0)    # It sort the array element in column wise
print(s)

## Filter In Numpy....

f1=np.array([10,14,26,31,42,53,67])
l1=[True,False,True,True,False,False,False]
print(f1[l1])

l2=(f1%2==0) # This is the condition for filtering.
print(l2)
print(f1[l2])


l3=(f1>50) # This is the condition for filtering.
print(l3)
print(f1[l3]) # Here The Content is return 

[[ 8 10 12]
 [ 5  9 13]]
[[ 8 10 12]
 [ 5  9 13]]
[[-6 -6 -6]
 [ 3  1 -1]]
[[-6 -6 -6]
 [ 3  1 -1]]
[[ 7 16 27]
 [ 4 20 42]]
[[ 7 16 27]
 [ 4 20 42]]
[[0.14285714 0.25       0.33333333]
 [4.         1.25       0.85714286]]
[ 6  8 10 12]
8 10 12 5 9 13 8
10
12
5
9
13
8 is in index (0, 0)
10 is in index (0, 1)
12 is in index (0, 2)
5 is in index (1, 0)
9 is in index (1, 1)
13 is in index (1, 2)
[12  3  4  5 78  3  4  5]
[[12  3  4  5]
 [78  3  4  5]]
[12  3  4  5 78  3  4  5]
[[12  3  4  5]
 [78  3  4  5]]
[[[12 78]
  [ 3  3]
  [ 4  4]
  [ 5  5]]]
[[12 78]
 [ 3  3]
 [ 4  4]
 [ 5  5]]
[[10 20]
 [30 40]
 [ 1  2]
 [ 3  4]]
[[10 20  1  2]
 [30 40  3  4]]
[array([10, 55]), array([90]), array([78])]
[array([[10, 20]]), array([[30, 40]]), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64)]
(array([5, 7]),)
(array([2, 3, 4, 5, 7]),)
(array([1]), array([0]))
[10 55 78 90]
[[ 10  20 167]
 [  9 456 900]]
[[167  20   9]
 [456 900  10]]
[10 26 31]
[ True  True  True False  Tru

## Function In Numpy

In [62]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1.mean()) # Find Out The Mean.
print(a1.diagonal()) # Print The Diagonal Elements
print(a1.trace()) # it return the sum of the diagonal element.
print(a1.transpose()) # Transpose the matrix.
print(np.ptp(a1)) # Peek to peek that means it show the difference between highest and lowest value in array.
print(a1.max()) # print maximum value
print(a1.min()) # Print The Minimum value.
print(a1.sum()) # return the sum of all element.
print(a1.prod()) # return the product of all the element.

print(a1.std()) # Find The standard deviation
print(a1.var()) # Find The variance 

a2=a1.reshape(-1)
print(a2) # make 2D array into 1D Array.

a3=a1.flatten()
print(a3)  # it convert 2D array into 1D array. If you changes in flatten array the it does not impact the original array.
a3[4]=1000
print(a3)
print(a2)

a4=a1.ravel()
print(a4)
a4[2]=999
print(a4) # it convert 2D array into 1D array. If you changes in ravel array the it  impact the original array.
print(a2)

# copy() and view() both are similar to flatten() and ravel()..........

r=np.array([1,4,7,9])
c=r.copy()
c[0]=10
print(c) # copy() does not affect original array.
print(r)

v=r.view()
print(v)
v[2]=70
print(v) # view() affect both the array i.e original as well as view array
print(r)

print(v.base) # view() method return the reference of the original srrsy
print(c.base) # copy() method return the None value


##### Resize()########3

d1=np.array([[1,2,3],[4,5,6]])
d2=d1.resize((3,4),refcheck=False)
print(d2)

5.0
[1 5 9]
15
[[1 4 7]
 [2 5 8]
 [3 6 9]]
8
9
1
45
362880
2.581988897471611
6.666666666666667
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[   1    2    3    4 1000    6    7    8    9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[  1   2 999   4   5   6   7   8   9]
[  1   2 999   4   5   6   7   8   9]
[10  4  7  9]
[1 4 7 9]
[1 4 7 9]
[ 1  4 70  9]
[ 1  4 70  9]
[ 1  4 70  9]
None
None
